#!/bin/bash
# A simple demonstration of variables
# Ryan 6/5/2018
 
echo My name is $0 and I have been given $# command line arguments
echo Here they are: $*
echo And the 2nd command line argument is $2
